version: '3.0'
services:
  node:
    container_name: app
    build: .
    ports:
      - ${PORT}:${PORT}
    networks:
      - rest-network
    depends_on:
      - postgres
    volumes:
      - ./src:/usr/app/src
    restart: always
  postgres:
    container_name: postgres
    build: ./src/database
    volumes:
      - ./src/database/data:/var/lib/postgresql/data:rw
      - ./src/database/logs:/var/lib/postgresql/logs:rw
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - rest-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
networks:
  rest-network:
    driver: bridge
